#!/usr/bin/env bash
# =============================================================================
# PHASE 3 — vLLM Inference Server
# =============================================================================
# Starts Brain. All settings driven from config/models.yml.
# To swap the model: edit models.yml → re-run this script.
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${REPO_ROOT}/.env" 2>/dev/null || true

MODELS_DIR="${MODELS_DIR:-/opt/models}"

get_field() {
    python3 -c "
import yaml
with open('${REPO_ROOT}/config/models.yml') as f:
    cfg = yaml.safe_load(f)
val = cfg.get('$1', {}).get('$2', '')
# YAML true -> Python True prints as 'True'; callers test for 'true'.
if isinstance(val, bool):
    val = str(val).lower()
print(val if val is not None else '')
"
}

get_extra_env_flags() {
    python3 -c "
import yaml
with open('${REPO_ROOT}/config/models.yml') as f:
    cfg = yaml.safe_load(f)
env = cfg.get('$1', {}).get('extra_env', {}) or {}
for k, v in env.items():
    print(f'-e {k}={v}')
" 2>/dev/null || true
}

# Emit a field as compact JSON. Accepts either a YAML mapping or a pre-formatted
# JSON string in models.yml. Compact separators keep the result space-free so it
# survives the word-splitting VLLM_EXTRA_ARGS path below without extra quoting.
get_json_field() {
    python3 -c "
import yaml, json
with open('${REPO_ROOT}/config/models.yml') as f:
    cfg = yaml.safe_load(f)
val = cfg.get('$1', {}).get('$2', None)
if val is None or val == '':
    print('')
elif isinstance(val, str):
    print(''.join(val.split()))
else:
    print(json.dumps(val, separators=(',', ':')))
"
}

echo "========================================================"
echo " spark-sovereign — Phase 3: vLLM Inference Server"
echo "========================================================"

# Stop all GPU model containers first to free memory before starting.
echo ">>> Stopping existing GPU model containers..."
for name in brain qwen-brain nemotron-nano asr-server tts-server; do
    if docker ps -q --filter "name=^${name}$" | grep -q .; then
        docker stop "${name}" 2>/dev/null && echo "    stopped ${name}" || true
    fi
    docker rm -f "${name}" 2>/dev/null || true
done

# ── Brain ─────────────────────────────────────────────────────────────────────
BRAIN_IMAGE=$(get_field brain docker_image)
BRAIN_PATH=$(get_field brain local_path)
BRAIN_NAME=$(get_field brain served_name)
BRAIN_PORT=$(get_field brain port)
# Fall back to loopback when models.yml predates bind_host, so an older config
# tightens rather than silently staying open to the whole LAN.
BRAIN_HOST=$(get_field brain bind_host)
BRAIN_HOST="${BRAIN_HOST:-127.0.0.1}"
# Bearer token for /v1. Lives in .env (gitignored) — never models.yml, which is
# public. Auto-provisioned on first run so the sequence 00→01→02→03 leaves a
# working, authenticated Brain with no manual step.
#
# Secrecy properties, deliberately:
#   - written only to .env, which .gitignore already covers
#   - .env forced to chmod 600 (owner-only) whenever we touch it
#   - passed to the container as VLLM_API_KEY, NOT --api-key, so the secret
#     never lands on the process command line where `ps aux` would show it
#   - printed in full exactly once, here, on the terminal that ran the script
BRAIN_API_KEY="${BRAIN_API_KEY:-}"
ENV_FILE="${REPO_ROOT}/.env"

if [ -z "${BRAIN_API_KEY}" ]; then
    if ! command -v openssl >/dev/null 2>&1; then
        echo "WARN: openssl not found — cannot generate BRAIN_API_KEY."
        echo "      Brain will start WITHOUT authentication."
    else
        BRAIN_API_KEY="$(openssl rand -hex 32)"
        touch "${ENV_FILE}"
        chmod 600 "${ENV_FILE}"
        if grep -q '^BRAIN_API_KEY=' "${ENV_FILE}" 2>/dev/null; then
            # Replace the blank placeholder rather than appending a duplicate.
            sed -i "s|^BRAIN_API_KEY=.*|BRAIN_API_KEY=${BRAIN_API_KEY}|" "${ENV_FILE}"
        else
            printf '\n# Auto-generated by scripts/03_vllm_servers.sh. Keep private.\nBRAIN_API_KEY=%s\n' \
                "${BRAIN_API_KEY}" >> "${ENV_FILE}"
        fi
        echo ""
        echo ">>> Generated a new BRAIN_API_KEY and saved it to .env (chmod 600)."
        echo "    Every script in this repo reads it from there automatically."
    fi
else
    # Key already present — make sure the file holding it is not world-readable.
    [ -f "${ENV_FILE}" ] && chmod 600 "${ENV_FILE}"
fi
BRAIN_UTIL=$(get_field brain gpu_memory_utilization)
BRAIN_CTX=$(get_field brain max_model_len)
BRAIN_KV=$(get_field brain kv_cache_dtype)
BRAIN_SEQS=$(get_field brain max_num_seqs)
BRAIN_TOOL=$(get_field brain tool_call_parser)
BRAIN_REASON=$(get_field brain reasoning_parser)
BRAIN_BATCHED=$(get_field brain max_num_batched_tokens)
BRAIN_MM=$(get_field brain limit_mm_per_prompt)
BRAIN_QUANT=$(get_field brain quantization)
BRAIN_MOE_BACKEND=$(get_field brain moe_backend)
BRAIN_SPEC_CONFIG=$(get_json_field brain speculative_config)
BRAIN_EAGER=$(get_field brain enforce_eager)
BRAIN_REASON_PLUGIN=$(get_field brain reasoning_parser_plugin)
BRAIN_ASYNC=$(get_field brain async_scheduling)
BRAIN_ENTRYPOINT=$(get_field brain entrypoint_mode)
BRAIN_PREFIX_CACHE=$(get_field brain enable_prefix_caching)
BRAIN_EXTRA_ENV=$(get_extra_env_flags brain)

echo ""
echo ">>> Starting Brain: ${BRAIN_NAME} on port ${BRAIN_PORT}"

BRAIN_MODEL_PATH="/models/$(basename "${BRAIN_PATH}")"

if [ "${BRAIN_ENTRYPOINT}" = "serve" ]; then
    # ── Avarok image ──────────────────────────────────────────────────────────
    # Avarok entrypoint reads: MODEL, PORT, HOST, MAX_MODEL_LEN, GPU_MEMORY_UTIL,
    # MAX_NUM_SEQS as env vars. All other vLLM flags go into VLLM_EXTRA_ARGS.
    EXTRA_ARGS=""
    EXTRA_ARGS+=" --kv-cache-dtype ${BRAIN_KV}"
    EXTRA_ARGS+=" --trust-remote-code"
    EXTRA_ARGS+=" --enable-auto-tool-choice"
    EXTRA_ARGS+=" --tool-call-parser ${BRAIN_TOOL}"
    # Optional: models with no thinking mode (e.g. Qwen3-Coder-Next) leave this blank.
    [ -n "${BRAIN_REASON}" ]       && EXTRA_ARGS+=" --reasoning-parser ${BRAIN_REASON}"
    [ -n "${BRAIN_REASON_PLUGIN}" ] && EXTRA_ARGS+=" --reasoning-parser-plugin ${BRAIN_MODEL_PATH}/${BRAIN_REASON_PLUGIN}"
    [ -n "${BRAIN_BATCHED}" ]      && EXTRA_ARGS+=" --max-num-batched-tokens ${BRAIN_BATCHED}"
    [ -n "${BRAIN_QUANT}" ]        && EXTRA_ARGS+=" --quantization ${BRAIN_QUANT}"
    [ -n "${BRAIN_MOE_BACKEND}" ]  && EXTRA_ARGS+=" --moe-backend ${BRAIN_MOE_BACKEND}"
    [ -n "${BRAIN_SPEC_CONFIG}" ]  && EXTRA_ARGS+=" --speculative-config ${BRAIN_SPEC_CONFIG}"
    [ "${BRAIN_EAGER}" = "true" ]  && EXTRA_ARGS+=" --enforce-eager"
    [ -n "${BRAIN_MM}" ]           && EXTRA_ARGS+=" --limit-mm-per-prompt ${BRAIN_MM}"
    [ "${BRAIN_ASYNC}" = "true" ]  && EXTRA_ARGS+=" --async-scheduling"
    [ "${BRAIN_PREFIX_CACHE}" = "true" ] && EXTRA_ARGS+=" --enable-prefix-caching"
    # NOTE: the key is NOT added to EXTRA_ARGS. It goes in as VLLM_API_KEY
    # below, which vLLM reads directly, keeping it off the command line.

    # shellcheck disable=SC2086
    docker run -d --name brain \
        --gpus all --ipc host --network host \
        --restart no \
        -e MODEL="${BRAIN_MODEL_PATH}" \
        -e HOST="${BRAIN_HOST}" \
        -e PORT="${BRAIN_PORT}" \
        -e MAX_MODEL_LEN="${BRAIN_CTX}" \
        -e GPU_MEMORY_UTIL="${BRAIN_UTIL}" \
        -e MAX_NUM_SEQS="${BRAIN_SEQS}" \
        -e VLLM_EXTRA_ARGS="${EXTRA_ARGS}" \
        ${BRAIN_API_KEY:+-e VLLM_API_KEY="${BRAIN_API_KEY}"} \
        ${BRAIN_EXTRA_ENV} \
        -v "${MODELS_DIR}:/models" \
        -v vllm-cache:/root/.cache/vllm \
        "${BRAIN_IMAGE}"
else
    # ── Standard vLLM image ───────────────────────────────────────────────────
    # shellcheck disable=SC2086
    docker run -d --name brain \
        --gpus all --ipc host --network host \
        --restart no \
        ${BRAIN_API_KEY:+-e VLLM_API_KEY="${BRAIN_API_KEY}"} \
        ${BRAIN_EXTRA_ENV} \
        -v "${MODELS_DIR}:/models" \
        -v vllm-cache:/root/.cache/vllm \
        "${BRAIN_IMAGE}" \
            --model "${BRAIN_MODEL_PATH}" \
            --served-model-name "${BRAIN_NAME}" \
            --host "${BRAIN_HOST}" --port "${BRAIN_PORT}" \
            --gpu-memory-utilization "${BRAIN_UTIL}" \
            --max-model-len "${BRAIN_CTX}" \
            --kv-cache-dtype "${BRAIN_KV}" \
            ${BRAIN_BATCHED:+--max-num-batched-tokens "${BRAIN_BATCHED}"} \
            ${BRAIN_QUANT:+--quantization "${BRAIN_QUANT}"} \
            ${BRAIN_MOE_BACKEND:+--moe-backend "${BRAIN_MOE_BACKEND}"} \
            ${BRAIN_SPEC_CONFIG:+--speculative-config "${BRAIN_SPEC_CONFIG}"} \
            $([ "${BRAIN_EAGER}" = "true" ] && echo "--enforce-eager") \
            --trust-remote-code \
            --enable-auto-tool-choice \
            --tool-call-parser "${BRAIN_TOOL}" \
            ${BRAIN_REASON:+--reasoning-parser "${BRAIN_REASON}"} \
            ${BRAIN_REASON_PLUGIN:+--reasoning-parser-plugin "${BRAIN_MODEL_PATH}/${BRAIN_REASON_PLUGIN}"} \
            --max-num-seqs "${BRAIN_SEQS}" \
            ${BRAIN_MM:+--limit-mm-per-prompt "${BRAIN_MM}"} \
            $([ "${BRAIN_PREFIX_CACHE}" = "true" ] && echo "--enable-prefix-caching") \
            $([ "${BRAIN_ASYNC}" = "true" ] && echo "--async-scheduling")
fi

echo "    Container 'brain' started → http://localhost:${BRAIN_PORT}/v1"
echo "    Watch: docker logs brain -f"
echo ""
echo "Waiting for Brain to be ready..."
# Header is sent unconditionally: vLLM ignores it when --api-key is unset, and
# /v1 returns 401 without it once a key is configured.
until curl -sf -H "Authorization: Bearer ${BRAIN_API_KEY}" \
        "http://localhost:${BRAIN_PORT}/v1/models" >/dev/null 2>&1; do
    if ! docker ps -q --filter "name=^brain$" --filter "status=running" | grep -q .; then
        echo "ERROR: brain container exited. Check: docker logs brain"
        exit 1
    fi
    sleep 5
done

echo ""
echo "========================================================"
echo " Brain loaded and serving."
echo "  Model : ${BRAIN_NAME}"
echo "  URL   : http://localhost:${BRAIN_PORT}/v1"
echo "  Memory: util=${BRAIN_UTIL} → ~$(python3 -c "print(round(121.69 * ${BRAIN_UTIL}))")GB reserved by vLLM (weights + KV cache)"
echo "========================================================"
echo ""
echo " NEXT STEP: Open OpenClaw → run the onboard setup wizard"
echo ""
echo " When the wizard asks — enter these values:"
echo ""
echo "  Provider type   : OpenAI-compatible endpoint"
echo "  Base URL        : http://localhost:${BRAIN_PORT}/v1"
echo "  Model ID        : ${BRAIN_NAME}"
if [ -n "${BRAIN_API_KEY}" ]; then
echo "  API key         : ${BRAIN_API_KEY}"
echo "                    ^ REQUIRED — /v1 returns 401 without it. Paste this"
echo "                      into OpenClaw's wizard. It is stored in .env, so"
echo "                      re-read it any time with:  grep BRAIN_API_KEY .env"
else
echo "  API key         : unused  (any string works — no key configured)"
fi
echo "  Context window  : ${BRAIN_CTX}"
echo ""
echo " Everything else (agent name, personality, voice, memory,"
echo " Telegram, workspace) is configured inside OpenClaw's wizard."
echo "========================================================"
